services:
  - type: web
    name: kniha-jizd-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: 7544773821:AAF5hwW3lmxANx-ETjve7rajJC_g5AXFdpE
